export const men = {
  title: "Men Fashion",
  items: [
    { image: "assets/m1.jpg", price: "559" },
    { image: "assets/m2.jpg", price: "459" },
    { image: "assets/m3.jpg", price: "659" },
    { image: "assets/m4.jpg", price: "759" },
    { image: "assets/m5.jpg", price: "859" },
    { image: "assets/m6.jpg", price: "899" },
    { image: "assets/w1.jpg", price: "559" },
    { image: "assets/m6.jpg", price: "459" },
    { image: "assets/m8.jpg", price: "659" },
    { image: "assets/m7.jpg", price: "759" },
    { image: "assets/m2.jpg", price: "859" },
    { image: "assets/w5.jpg", price: "899" },
    { image: "assets/m9.jpg", price: "559" },
    { image: "assets/m2.jpg", price: "459" },
    { image: "assets/m3.jpg", price: "659" },
    { image: "assets/m4.jpg", price: "759" },
    { image: "assets/m2.jpg", price: "859" },
    { image: "assets/w5.jpg", price: "899" },
     { image: "assets/m1.jpg", price: "199" },
    { image: "assets/w2.jpg", price: "299" },
    { image: "assets/m3.jpg", price: "399" },
    { image: "assets/m4.jpg", price: "499" },
    { image: "assets/w5.jpg", price: "599" },
    { image: "assets/w10.jpg", price: "699" },
  ],
};

export const women = {
  title: "Women Fashion",
  items: [
    { image: "assets/w2.jpg", price: "559" },
    { image: "assets/w5.jpg", price: "459" },
    { image: "assets/w4.jpg", price: "659" },
    { image: "assets/w8.jpg", price: "759" },
    { image: "assets/w1.jpg", price: "859" },
    { image: "assets/w9.jpg", price: "899" },
    { image: "assets/w1.jpg", price: "559" },
    { image: "assets/w10.jpg", price: "459" },
    { image: "assets/w2.jpg", price: "659" },
    { image: "assets/w9.jpg", price: "759" },
    { image: "assets/s1.jpg", price: "859" },
    { image: "assets/w5.jpg", price: "899" },
     { image: "assets/w8.jpg", price: "199" },
    { image: "assets/w7.jpg", price: "299" },
    { image: "assets/w10.jpg", price: "399" },
    { image: "assets/w5.jpg", price: "499" },
    { image: "assets/w10.jpg", price: "599" },
    { image: "assets/w9.jpg", price: "699" },
  ],
};

export const kids = {
  title: "Kids Fashion",
  items: [
    { image: "assets/w1.jpg", price: "559" },
    { image: "assets/m2.jpg", price: "459" },
    { image: "assets/B2.jpg", price: "659" },
    { image: "assets/w4.jpg", price: "759" },
    { image: "assets/m2.jpg", price: "859" },
    { image: "assets/w5.jpg", price: "899" },
    { image: "assets/w5.jpg", price: "299" },
    { image: "assets/s5.jpg", price: "349" },
    { image: "assets/m2.jpg", price: "399" },
    { image: "assets/w7.jpg", price: "449" },
    { image: "assets/w10.jpg", price: "499"},
    { image: "assets/w9.jpg", price: "549" },
     { image: "assets/w1.jpg", price: "199" },
    { image: "assets/w2.jpg", price: "299" },
    { image: "assets/w3.jpg", price: "399" },
    { image: "assets/w4.jpg", price: "499" },
    { image: "assets/w5.jpg", price: "599" },
    { image: "assets/w10.jpg", price: "699" },
  ],
};

export const beauty = {
  title: "Beauty Products",
  items: [
    { image: "assets/B1.jpg", price: "199" },
    { image: "assets/b11.jpg", price: "299" },
    { image: "assets/b22.jpg", price: "399" },
    { image: "assets/b33.jpg", price: "499" },
    { image: "assets/b44.jpg", price: "599" },
    { image: "assets/b66.jpg", price: "699" },
    { image: "assets/b11.jpg", price: "559" },
    { image: "assets/m7.jpg", price: "459" },
    { image: "assets/b66.jpg", price: "659" },
    { image: "assets/b11.jpg", price: "759" },
    { image: "assets/b44.jpg", price: "859" },
    { image: "assets/w5.jpg", price: "899" },
     { image: "assets/b11.jpg", price: "199" },
    { image: "assets/w2.jpg", price: "299" },
    { image: "assets/w3.jpg", price: "399" },
    { image: "assets/b33.jpg", price: "499" },
    { image: "assets/b22.jpg", price: "599" },
    { image: "assets/b11.jpg", price: "699" },
  ],
};
